// Auto-generated scope-and-sequence data embedded as string constants.
// This avoids filesystem reads in the Next.js edge runtime.

export const SCOPE_DATA: Record<string, string> = {
  K: `# Garden City Public Schools

# **Grade K Scope and Sequence Draft 2024-2025**

|  | September | October | November | December | January | February | March | April | May | June |
| :---: | ----- | :---: | :---: | ----- | ----- | ----- | :---: | ----- | :---: | :---: |
| Reading | Unit 1: We are Readers Book #1  | Cont Unit 1: We are Readers"  Begin Unit 2: Emergent Reading—Looking Closely at Familiar Texts (If…Then…) | Cont Unit 2: Emergent Reading—Looking Closely at Familiar Texts (If…Then…) | Unit 3: Super Powers:  Reading with Print Strategies Book   | Cont Unit 3: Super Powers: Reading with Print Strategies Book   | Unit 4: Bigger Books, Bigger Reading Muscles Book #3  | Cont Unit 4: Bigger Books, Bigger Reading Muscles Book #3  |  Unit 5: Becoming Avid Readers | Cont Unit 5: Becoming Avid Readers  | Cont Unit 5: Becoming Avid Readers  |
| FUNdations | FUNdations: Unit 1 (12 weeks) | FUNdations: Unit 1 cont | FUNdations: Unit 1 cont | Finish Unit 1 Begin Unit 2 | FUNdations: Unit 2 (4 Weeks) | FUNdations: Unit 3 (6 Weeks) | FUNdations: Finish Unit 3 and Begin Unit 4 (4 Weeks) | FUNdations: Unit 5 (6 weeks)  | FUNdations: Finish Unit 5 | Review |
| Writing | [Unit 1: Learning How To Be a Writer:Launching the Writing Workshop](https://docs.google.com/document/d/1HvwlmzPt0DycSxv366D7PxE9m7qWTI0F1boLJrrwwpM/edit?tab=t.0) | [Unit 1: Learning How To Be a Writer:Launching the Writing Workshop cont](https://docs.google.com/document/d/1HvwlmzPt0DycSxv366D7PxE9m7qWTI0F1boLJrrwwpM/edit?tab=t.0) | [Unit 2: Writing List and Label Books to Communicate What We Know](https://docs.google.com/document/d/1YdXpHHTDXTJNU52XZdGNvy7ugh7mvFAcOyBV_Pcn8JE/edit?usp=sharing) | [Cont Unit 3:Writing Pattern Books](https://docs.google.com/document/d/1vhK3M-PiZqGhsEVaexcWN7PoYwmjpHwo8GxG3PPgrK0/edit?usp=sharing) | [Unit 3: Writing Pattern Books](https://docs.google.com/document/d/1vhK3M-PiZqGhsEVaexcWN7PoYwmjpHwo8GxG3PPgrK0/edit?usp=sharing) | [Unit 4: Informational Writing: Using Text Features to Teach Our Reader](https://docs.google.com/document/d/1SNEZGPIe-eQNlKw_1gglgp4-r0Dk0wjtv9CPKx-j7Eo/edit?usp=sharing) | [Unit 4: Informational Writing: Using Text Features to Teach Our Reader](https://docs.google.com/document/d/1SNEZGPIe-eQNlKw_1gglgp4-r0Dk0wjtv9CPKx-j7Eo/edit?usp=sharing) | [Unit 5: Sharing Our Thoughts about Books and Beyond: Writing Opinion Pieces Using Support](https://docs.google.com/document/d/1KCm1z9-OWhsgZsb1gZnhPmqqQrMssxuKqMF6jpUYheg/edit?usp=sharing) | [cont Unit 5: Sharing Our Thoughts about Books and Beyond: Writing Opinion Pieces Using Support](https://docs.google.com/document/d/1KCm1z9-OWhsgZsb1gZnhPmqqQrMssxuKqMF6jpUYheg/edit?usp=sharing) | [Unit 6: Perform, Celebrate, and Review](https://docs.google.com/document/d/1ojLjRNoccEtP7IvDWBrhLPcy63F8rEe1uzy-QH1PB3c/edit?usp=sharing) |
| Math  | **Unit 1**  Math in Our World  | **Unit 2** Numbers 1-10 | GC Measurement (length, height, volume, weight) **Unit 3** Flat Shapes All Around Us |  | **Unit 4** Understanding Addition and Subtraction | **Unit 5** Composing and Decomposing Numbers to 10 —------------- GC Coins Continue Adding within 10/Subtract **Grade K:** [Adaptations: Plants and Animals](https://docs.google.com/document/d/1iJ9QdwQVg65TAjLQajdzd8fAq-E_6X_M5pt04nZD9a8/edit?usp=sharing) (part of the Interdependent Relationships in Ecosystem unit - 3) **Grade K:** [Forces and Interactions: Pushes and Pulls](https://docs.google.com/document/d/1Zu8bNb__k4D9dKwrt__yQMJfo-zlIgxY4fO1cC1rqUw/edit?usp=sharing) **Grade K:** [Weather and Climate](https://docs.google.com/document/d/1aZSwyv3gHxuAwgTEwJmYH_6vbWHBaxBf8zPrXTGv064/edit?usp=sharing) **(throughout the year)**within 10 |  | **Unit 6** Numbers 0-20 | **Unit 7** Solid Shapes ALl Around Us | **Unit 8** Putting it All Together (TBD) |
| Science | **Grade K:** [Matter and its Interactions](https://docs.google.com/document/d/1Lcli9xr-uQbsNbMDIs5iL3pc_ufcnG5OOjed6aw0KSI/edit?usp=sharing) **Grade K:** [Weather and Climate](https://docs.google.com/document/d/1aZSwyv3gHxuAwgTEwJmYH_6vbWHBaxBf8zPrXTGv064/edit?usp=sharing)  **(throughout the year)**   |  |  |  |  |  |  | **Grade K:** [Interdependent Relationships in Ecosystems: Plants and Animals and their Environment](https://docs.google.com/document/d/1iJ9QdwQVg65TAjLQajdzd8fAq-E_6X_M5pt04nZD9a8/edit?usp=sharing) **Grade K:** [Weather and Climate](https://docs.google.com/document/d/1aZSwyv3gHxuAwgTEwJmYH_6vbWHBaxBf8zPrXTGv064/edit?usp=sharing) **(throughout the year)**  |  |  |
| Social Studies | **Unit 1:**  [Rules and Getting Along –  Our School Community](https://docs.google.com/document/d/1zPvB6vne094wLV1Y7Nsg84Ezboh0C7Z73wbm8yqiOvE/edit?usp=sharing)  |  | **Unit 2**  [All About Me, Families, Humans are special and unique](https://docs.google.com/document/u/0/d/1Z78NJdIvaprXemUUSSqWettuhDJcRsYMIfidTkys4LQ/edit) |  | **Unit 3**  Being a Good Citizen  |  | **Unit 4:**  Needs and Wants/Goods and Services – job fair |  | **Unit 5**  |  |
`,

  "1": `# Garden City Public Schools

# **Grade 1 Scope and Sequence 2024-2025**

|  | September | October | November | December | January | February | March | April | May | June |
| ----- | ----- | :---: | :---: | :---: | :---: | ----- | ----- | ----- | :---: | :---: |
| Reading | Unit 1: Building Good Reading Habits Book #1 | Cont Unit 1: Building Good Reading Habits" Book #1 / Unit 2 Word Detectives | cont Unit 2: Word Detectives Stand Alone Book | Cont Unit 2: Word Detectives Stand Alone Book Unit 3: Learning All about the World | Unit 3: Learning All about the World  | Cont Unit 3: Learning All about the World  Book #2/ Unit 4: Readers Have Big Jobs to Do | Unit 4: Readers Have Big Jobs to Do  Book #3 | Cont Unit 4:Readers Have Big Jobs to Do  Book #3/Unit 5: Meeting Characters and Learning Lessons | Unit 5: Meeting Characters and Learning Lessons Book #4 | Cont Unit 5: Meeting Characters and Learning Lessons Book #4 |
| FUNdations | Unit 1 (Weeks 1-3) | Unit 2 (3 Weeks) Begin Unit 3 (2 Weeks) | Unit 4 (2 Weeks) Begin Unit 5 (1 Week) | Cont Unit 5  Unit 6 | Unit 7 (3 Weeks) Begin Unit 8 | Unit 8 cont Begin Unit 9 | Unit 10 (3 weeks) Begin Unit 11 | Cont Unit 11  Begin Unit 12 | Cont Unit 12  Begin Unit 13 | Unit 14 |
| Writing | Unit 1: Building a Community of Writers: Launching Writing Workshop | Unit 2: Narrative Writing: Small Moments" Book #1 | Unit 2:  Narrative Writing: Small Moments" Book #1  | Unit 3: A Close Look at Informational Text Writing | Unit 3: A Close Look at Informational Text Writing/ Unit 4: What's Your Opinion? | Unit 4: What's Your Opinion?  | cont Unit 4: What's Your Opinion?/ Unit 5: Writing Shared Research: Working Together to Create Informational Text  | cont Unit 5: Writing Shared Research: Working Together to Create Informational Text/Unit 6: Having Conversations with Characters Through Letters  | Unit 6: Having Conversations with Characters Through Letters | Unit 7: Poetry Writing/ Revisit Small Moments |
| Math | **Unit 1**  Adding Subtracting, and Working with Data | **Unit 2** Addition and Subtraction Story Problems |  | **Unit 3** Adding and Subtracting within 20 |  | **Unit 4** Numbers to 99   | **Unit 5** Adding within 100 | **Unit 6**  Length Measurements within 120  | **Unit 7** Geometry and Time —------------------ (GC Section on Coins) |  |
| Science |   | **Unit 1:**  Think Like a Scientist [Space Systems: Patterns and Cycles](https://docs.google.com/document/d/1uVRV9sTBZKKDk4_5x4YOWIrIaPynI1KMoJU0kN4tOi4/edit?usp=sharing) **Mid Oct to mid November** |  |  |  | **Unit 2:**   [Waves: Light and Sound](https://docs.google.com/document/d/1MTTzsF-3X5ad5VEJuomKgllQ5pXVT5rPnPupXy__p60/edit?usp=sharing) **Feb - Mid March**  |  |  | **Unit 3:**  [Structure, Functions and Information Processing](https://docs.google.com/document/d/1Damg08vqu4v34A6Z4VxfZWF3VLPehjBozayPuzGjiRA/edit?usp=sharing) **May to June** |  |
| Social Studies | **Unit 1:**  [School and classroom citizenship](https://docs.google.com/document/d/1zR-VA8Kd_SLX9sYriM82G_XKs1KAiGQdBm5H-UZU2c8/edit?usp=sharing) **Sept- Mid Oct** |  |  | **Unit 2:**  [Families Now and Long Ago](https://docs.google.com/document/d/1V9Eq9qOibPXv2e6qERbwn6MEm74S4hNOn4ZcpaGiKXo/edit?usp=sharing) **Mid Nov- End of January** Needs and Wants |  |  | **Unit 3** [School Community](https://docs.google.com/document/d/1Zvn54kNEjp9mlZphcuuFpbqbprewuf_mb55feSd-swY/edit?usp=sharing) **Mid March - April "All About My School" writing connection?** |  |  |  |
`,

  "2": `# Garden City Public Schools

# **Grade 2 Scope and Sequence 2025-2026 *work in progress**

|  | September | October | November | December | January | February | March | April | May | June |
| :---: | ----- | :---: | ----- | :---: | ----- | :---: | ----- | :---: | :---: | :---: |
| **Reading** | Unit 1: Reading Growth Spurts Book #1   | Cont Unit 1: Reading Growth Spurt Book #1  | Unit 2: Becoming Experts Reading Nonfiction Book 2: | Becoming Experts Reading Nonfiction Book #2  |  *3: Growing Word Solving Muscles* | Unit 4: Characters and Their Stories If...Then...Book  | Unit 4: Characters and Their Stories If...Then...Book   | Unit 5: Bigger Books Mean Amping Up Reading Power (Book 3)   | Unit 6: Reading Nonfiction Cover to Cover If....Then...Book  | Unit 6: Reading Nonfiction Cover to Cover If....Then...Boo |
| **Writing** | [The Writing Revolution Resource](https://docs.google.com/document/d/1pWrndG8QtPVuc0rbNmsVd8S1SzEAF3MKT-PJQm-MG-w/edit?usp=sharing)  | [Unit 1: Lessons from the Masters-- Small Moments and Narrative Writing Book # 1](https://docs.google.com/document/d/143KGakFXj_taL8CiW6EY6cKvAB67HK2juHwdZ2dqXTY/edit?usp=sharing)  | [Unit 2: How to Guide for Writing Nonfiction" Stand-Alone Book](https://docs.google.com/document/d/1dfOr7FgHJY0fJoDclE84HFiGgFovX4oeQBG9e0Ngnmo/edit?usp=sharing) | [Unit 2: "How to Guide for Writing Nonfiction" Stand-Alone Book](https://docs.google.com/document/d/1dfOr7FgHJY0fJoDclE84HFiGgFovX4oeQBG9e0Ngnmo/edit?usp=sharing) | Unit 3: Realistic Fiction Stories [SLIDE DECK](https://docs.google.com/presentation/d/1bV_LBFhTe7qhoQq6hAP8fQ9kMd29vOh3QDacb_j-9ks/edit?usp=sharing) | Unit 4: Writing with Clarity [SLIDE DECK](https://docs.google.com/document/d/1IuC19-iqnKiHJd8qKgwpofa-YrszjCXnHmPyDSjx9Ss/edit?usp=sharing) | Unit 4: Writing with Clarity [SLIDE DECK](https://docs.google.com/document/d/1IuC19-iqnKiHJd8qKgwpofa-YrszjCXnHmPyDSjx9Ss/edit?usp=sharing) | Unit 5: Nonfiction Research Writing [RESOURCES](https://docs.google.com/document/d/1wKmkaSPf8wZobLY2ASocgS7v0KwMTkH28QoJ3K430CM/edit?usp=sharing) | Unit 6: Writing About Reading Opinion Writing Book #3 [RESOURCES](https://docs.google.com/document/d/1L8FzzIjWZOITHHELoz5GuV7aJdg_rd4w1HmRDNzkvqs/edit?usp=sharing) | Unit 6: Writing About Reading Opinion Writing Book #3 [RESOURCES](https://docs.google.com/document/d/1L8FzzIjWZOITHHELoz5GuV7aJdg_rd4w1HmRDNzkvqs/edit?usp=sharing) |
| **[Math](https://docs.google.com/spreadsheets/d/19RngU9Fr6c46fodnnsDZmSeX1h76Eleo/edit?gid=39140444#gid=39140444)** | [**Unit 1**](https://sites.google.com/gardencity.k12.ny.us/curriculumhub/grade-2/grade-2-math/grade-2-unit-1)  Adding Subtracting, and Working with Data  |  | [**Unit 2**](https://sites.google.com/gardencity.k12.ny.us/curriculumhub/grade-2/grade-2-math/grade-2-unit-2) Adding and Subtracting within 100 | [**Unit 3**](https://sites.google.com/gardencity.k12.ny.us/curriculumhub/grade-2/grade-2-math/grade-2-unit-3) Measuring Length | [**Unit 4**](https://sites.google.com/gardencity.k12.ny.us/curriculumhub/grade-2/grade-2-math/grade-2-unit-4) Addition and Subtraction on the Number Line | [**Unit 5**](https://sites.google.com/gardencity.k12.ny.us/curriculumhub/grade-2/grade-2-math/grade-2-unit-5) Numbers to 1,000 | [**Unit 6**](https://sites.google.com/gardencity.k12.ny.us/curriculumhub/grade-2/grade-2-math/grade-2-unit-6) Adding and Subtracting within 1,000 | [**Unit 7**](https://sites.google.com/gardencity.k12.ny.us/curriculumhub/grade-2/grade-2-math/grade-2-unit-7) Geometry, Time, and Money *\\*Money will be taught first* |  | [**Unit 8**](https://sites.google.com/gardencity.k12.ny.us/curriculumhub/grade-2/grade-2-math/grade-2-unit-8) Equal Groups |
| **Science** | **[Structure and Properties of Matter (Material Magic)](https://docs.google.com/document/d/1PFtfpvxQjX5M-Md0foUwDkCbvLg-nXiT9wd0TefnQus/edit?usp=sharing)** |  |  | **[Earth's Systems: Processes that Shape the Earth (Work of Water)](https://docs.google.com/document/d/1kIR9cvXK_XwuPKlz5cYbTp3uNiwRu9uuBryv2WopY60/edit?usp=sharing)** |  |  | **[Interdependent Relationships in Ecosystems (Animal Adventures)](https://docs.google.com/document/d/1FNvybR-WBTtCNMY4c8saCF2nFFsUx3nNFmN7iCvBcUI/edit?usp=sharing)** |  | [**Interdependent Relationships in Ecosystems (Plant Adventures)**](https://docs.google.com/document/d/1CBKIpY8wuLIm0I8xE01Rg3GbfXOGEH2cSVFASvm8tR4/edit?usp=sharing) |  |
| **Social Studies** | **UNIT 1**  [Citizenship: Building Caring Communities](https://docs.google.com/document/d/16vXddrXUxAIWFQSLCxUe0pozEHBNoHpOb8RKGLNllnY/edit?usp=sharing)       |  | **UNIT 2**  [Exploring Different Communities – Urban, Suburban, and Rural Communities](https://docs.google.com/document/d/1qNmhf_2ladnxOYiDvXDyhyjIGYp07jsAtlaPK3C97DQ/edit?usp=sharing) |  | **UNIT –** [PBL Main Street](https://docs.google.com/document/d/1idvh5jfZ0e1XOm0Ectl7Q-qHpYyl1hwRUxvBKwg4KDI/edit?usp=sharing) **– [Feedback Document](https://docs.google.com/document/d/1oh6byqohJVI7hjxUg3fh9Pic9SWvqUVkpoT0kfpYCa8/edit?usp=sharing)** |  |  |  |  |  |
|  |  |  |  |  | **UNIT 3** [GC Then and Now](https://docs.google.com/document/d/1HtYGpQxV3xZBkugIJyvgOfcJKgz9tLUH5N04MSDh9VA/edit?usp=sharing) |  | **Unit 4 Economics** |  | [PBL Main Street](https://docs.google.com/document/d/1idvh5jfZ0e1XOm0Ectl7Q-qHpYyl1hwRUxvBKwg4KDI/edit?usp=sharing) Culmination |  |
| **Music/Art** | [General Music Scope and Sequence](https://docs.google.com/document/d/1DqOeJutB2lAq_Yz7iepAVV1lrtI7is962NsH5JeLDs8/edit?usp=sharing) [Art Scope and Sequence](https://docs.google.com/presentation/d/1BmbYZVy2XJwWhNhtSa7c6E2TJj8oGJEiEeFhHkaPdhY/edit?usp=sharing) |  |  |  |  |  |  |  |  |  |
`,

  "3": `# Garden City Public Schools

# **Grade 3 Scope and Sequence 2023-2024**

|  | September | October | November | December | January | February | March | April | May | June |
| ----- | ----- | :---: | ----- | ----- | ----- | ----- | :---: | :---: | ----- | :---: |
| Reading | Unit 1: Building a Reading Life Book #1 | Cont Unit 1: "Building a Reading Life" Book #1  Begin Unit 2: Mystery Foundational Skills in Disguise - Stand Alone Book  | Cont Unit 2: Mystery Foundational Skills in Disguise - Stand Alone Book     Begin Unit 3:     Reading To Learn - Book 1 | Unit 3:  Reading To Learn - Book 1/Begin Unit 4 Character Studies- Book 3  | Unit 4: Character Studies- Book 3/ Begin Unit 5 Research Clubs - Elephants, Penguins, and Frogs Book 4    | Cont Unit 5: Unit 5 Research Clubs - Elephants, Penguins, and Frogs Book 4   |  Unit 6: Test Prep Unit | cont Unit 6: Test Prep/ cont  Unit 5: "Research Clubs—Elephants, Penguins and Frogs" Book #4 | Cont Unit 7: Series Book Clubs | Cont Unit 7:Book Clubs |
| Writing | Unit 1: Crafting True Stories Book #1 | Cont Unit 1: Crafting True Stories Book #1  |   Cont Unit 1: Crafting True Stories Book #1/ Begin Unit 2: Art of Informational Writing - Book 2 | Cont Unit 2: Art of Informational Writing - Book 2/ Begin Unit 3 Baby Literary Essay | Cont Unit 3:  Baby Literary Essay/ Begin Unit 4: Writing About Research Book #3  | Cont Unit 4: Changing the World Book #3 | Unit 5: *T*est Prep - Constructed Response and Long Response (CLEAR) | Unit 6: "Writing about Research" | Unit 7: Once Upon a Time-Writing or Adapting Fairy Tales" Book #4 Opinion Writing? | Cont Unit 7: Once Upon a Time-Writing or Adapting Fairy Tales" Book #4 Opinion Writing? |
| Fundations |  | **Unit 1/Unit 2** | **Unit 2/Unit 3** | **Unit 3/ Unit 4** | **Unit 4/Unit 5** | **Unit 5** | **Unit 6** | **Unit 6** | **Unit 7** |  |
| Math | **Unit 1**  Introducing Multiplication | **Unit 2** Area and Multiplication | **Unit 3**  Wrapping Up Addition & Subtraction w/in 1000 —----------------------- GC Two-Step Word Problems |  | **Unit 4**  Relating Multiplication to Division | **Unit 5** Fractions as Numbers |  | **Unit 6** Measuring Length, Time, Liquid Volume, & Weight —----------------------------------- Review for State Assessment |  | **Unit 7** Two-dimensional Shapes and Perimeter —--------------- Post-Test Content Units 6A&7 |
| Science |  **Grade 3:** [Earth's Systems: Weather and Climate](https://docs.google.com/document/d/1J8wvkf2HJXtBtOqQ0ke5ezJuzQJ702mndD1wu_fzovQ/edit?usp=sharing)  |  |  | **Grade 3:** [Interdependent Relationships in Ecosystems](https://docs.google.com/document/d/1g2cVEk8rmynqpZdJUB5vNdU9tE6UhyqvBCUD-sZ0g98/edit?usp=sharing) |  |  |  **Grade 3:** [Forces and Interactions](https://docs.google.com/document/d/1FBQeNrReF0BTfu4XoQ2BbgKnskijuxmdOMA5wJECdXU/edit?usp=sharing) |  | **Grade 3:** . [Inheritance and Variation of Traits: Life Cycles and Traits](https://docs.google.com/document/d/1WdY2QiCC4uMG5tZOlh3uPcRhbACr2DrkpsbZKajsRFo/edit?usp=sharing) |  |
| Social Studies | **Unit 1** [Introduction to Geography](https://docs.google.com/document/d/13mSNDlHaKvLvRDIRCT-WkryZopA0nqSWG6TYEhSSX3Y/edit?usp=sharing)   |  |  **Unit 2** [Introduction to](https://docs.google.com/document/d/1CLipLO-0jRJN0i5OF7SgSk8emKdZx-PP7Xwou0xn0yY/edit?usp=sharing)  [Culture](https://docs.google.com/document/d/1CLipLO-0jRJN0i5OF7SgSk8emKdZx-PP7Xwou0xn0yY/edit?usp=sharing)  (We should decide if this gets attached to Geography next year or stays here and rolls right into Brazil.) | **UNIT 3–5:** Case Studies of [Brazil](https://docs.google.com/document/d/1Ca5bz9zI-uiMYGWDyEGNAp91zfPvzmmGWMQYBzq2xuc/edit?usp=sharing), [Africa (Nigeria),](https://docs.google.com/document/d/1CJrodxmg0eCsAIVpzSgSHT4Q3p4qrHlL0Zgw4323Yrg/edit?usp=sharing) China  |  |  |  |  |  | **Unit 5:**  Heritage Project (?)  [**Create a Country – PBL**](https://docs.google.com/document/d/1emMhEQDtQBVYEPRsUN46d4u1yYkAckarGj8ybQ-DxtY/edit?usp=sharing) (This is not getting a lot of traction and is on hold) |
`,

  "4": `# Garden City Public Schools

# **Grade 4 Scope and Sequence 2023-2024**

|  | September | October | November | December | January | February | March | April | May | June |
| ----- | ----- | :---: | :---: | ----- | :---: | :---: | ----- | ----- | ----- | :---: |
| **Reading** | Unit 1: Interpreting Characters Book #1 | Cont Unit 1: Interpreting Characters" Book #1 Begin Unit 2: Reading Weather, Reading the World (Native American Study) Book #2 | Cont Unit 2: "Reading Weather, Reading the World" Book #2 Begin Unit 3: "Details and Synthesis (Curricular Calendar) | Cont Unit 3: Details and Synthesis/ Begin Unit 4: Reading History – The American Revolution Book 3 | Unit 4: Reading History—The American Revolution Book #3 | Cont Unit 4: Reading History—The American Revolution" Book #3  | Unit 5: Test Prep Unit | Cont Unit 5:  Test Prep/Unit 6 Power and Perspective  | Cont Unit 6: Power and Perspective/ Begin Unit 7: "Power and Perspective | Unit 7:  Historical Fiction Book Clubs |
| **Writing** | Unit 1: The Arc of the Story--Writing Realistic Fiction Book #1 | Cont Unit 1: The Arc of the Story--Writing Realistic Fiction Book #1  | Unit 2: Boxes and Bullets-- Personal and Persuasive Essays Book #2 | Cont Unit 2: Boxes and Bullets-- Personal and Persuasive Essays Book #2 | Unit 3: Literary Essay--Writing about Fiction  Book #4 | Cont Unit 3: "Literary Essay--Writing about Fiction"  Book #4  | Unit 4: Test Prep - Constructed Response and Long Response (CLEAR)  | Unit 5: Bringing History to Life Book #3 | Cont Unit 5: Bringing History to Life OR Historical Fiction | Unit 6: Notebooks to Projects |
| **Math** | **Unit 1**  Fractions and Multiples | **Unit 2** Fraction Equivalence and Comparison | **Unit 3** Extending Operations to Fractions | **Unit 4** From Hundredths to Hundred-thousands | **Unit 5** Multiplicative Comparison and Measurement | **Unit 6** Multiplying and Dividing Multi-digit Numbers | **Unit 7** Angles and Angle Measurement | **Unit 8** Properties of Two-dimensional Shapes | Review for State Assessment | Post-Test Content from Units 4&5 |
| **Science** | **Grade 4:** [Structure, Function & Information Processing](https://docs.google.com/document/d/1E1_D4USyagy_N6huMZjCHchi-tKpM7yXJUcEpPYMeOw/edit?usp=sharing) |  |  | **Grade 4:** [Energy](https://docs.google.com/document/d/1hac1nhg7YXhOvNIGH-16S2rhyyDrbr0khZF-TRru1iM/edit?usp=sharing) |  |  | **Grade 4.** [Waves: Waves and Information](https://docs.google.com/document/d/1IF_WDuxwzO_dWs_3LIPuF8VwgMXqHVfJdVu120oQNao/edit?usp=sharing)  |  | **Grade 4.** [Earth's Systems: Processes that Shape the World](https://docs.google.com/document/d/1GcSgH9vqvLvFfVuDWL1gWbJQTPx0WY5-otOzUbbMw_o/edit?usp=sharing) |  |
| **Social Studies** | **Unit 1** [The Geography of NYS](https://docs.google.com/document/d/1ihpu1KydV5l3oUe_1WDHWtPhCSUpReWJWkO5Xst6zmY/edit?usp=sharing)  |  |  | **Unit 2:** [Native Americans](https://docs.google.com/document/u/0/d/1DuMvG-QN1R66M8WS5hgZHD1_ULx9SHfBy94WX10zObc/edit) [First Inhabitants of NYS](https://docs.google.com/document/u/0/d/1DuMvG-QN1R66M8WS5hgZHD1_ULx9SHfBy94WX10zObc/edit) |  |  | **[Museum of the History of NY – PBL](https://docs.google.com/document/d/1cxzwyVwIGNKkpVN81rcifoJWQMu5T1qlhQ6y-DkSGgM/edit?usp=sharing)** |  |  |  |
|  |  |  |  |  |  |  | **Unit 3**  [Colonial and Revolutionary Periods](https://docs.google.com/document/d/1WeJR1_9lmgeG69a-e2p_Fb9w8Ljng1lOxvjxipK1a1g/edit?usp=sharing) |  | **Not currently taught Unit 4:** Freedom and the New Nation (Government) : **Unit 5:** Making the Empire State: Immigration, Industry and the West |  |
`,

  "5": `# Garden City Public Schools

# **Grade 5 Scope and Sequence 2023-2024**

|  | September | October | November | December | January | February | March | April | May | June |
| ----- | ----- | :---: | :---: | ----- | :---: | :---: | ----- | :---: | ----- | :---: |
| **Reading** | Unit 1: Maintaining an Independent Reading Life/Notice and Note signposts Curricular Calendar | Unit 2: Interpretation Book Clubs Book #1  | Unit 3: Tackling Complexity--Moving up Levels of Nonfiction Book # 2 | Unit 3: Tackling Complexity--Moving up Levels of Nonfiction Book # 2 Unit 4: Argument and Advocacy | Unit 4: Argument and Advocacy- Book #3 | Cont Unit 4: Argument and Advocacy Book #3  | Unit 5: Test Prep Unit | Cont - Unit 5 Test Prep/ Begin Unit 6: Reading in the Content Area - We the People  | Cont Unit 6: Reading in the Content Area - We the People  | Unit 6: Fantasy Book Clubs Revisited |
| **Writing** | Unit 1: Narrative Craft Book #1 | Cont Unit : Narrative Craft Book #1 Begin Unit 2: Journalism | Cont Unit 2: Journalism | Unit 3: Literary Essay (Stand-alone Book) | Unit 4:  Informational Research-based Argument Essay - Book 4  | Cont Unit 4: Informational Research-based Argument Essay - Book 4 | Unit 5: Test Prep - Constructed Response and Long Response (CLEAR)  | Unit 6: Lens of History Writing--We The People | Unit 7: Choice Writing: Review portfolio and select a draft or published piece to strengthen any genre | Unit 7: Choice Writing: Review portfolio and select a draft or published piece to strengthen any genre |
| **Math** | **Unit 1** Finding Volume | **Unit 2** Fractions as Quotients and Fraction Multiplication | **Unit 3** Multiplying and Dividing Fractions | **Unit 4** Wrapping Up Multip. & Divi. with Multi-Digit Numbers | **Unit 5** Place Value Patterns and Decimal Operations |  | **Unit 6** More Decimal and Fraction Operations | **Unit 7** Shapes on the Coordinate Plane (B) —---------------------------------- Review and State Test —---------------------------------- Post-Test Content Unit 7 section A/C  |  | Putting it All Together/Preparing for Grade 6  (PEMDAS, standard algorithm division…) |
| **Science** | **Grade 5.** [Matter and Energy in Organisms and Ecosystems](https://docs.google.com/document/d/1BMcEQke4jXqQTgejb2yJJFWqVIBccg74SEGzdAjZzgM/edit?usp=sharing) |  |  | **Grade 5.** [Structure and Properties of Matter](https://docs.google.com/document/d/1pr7TUQ0ednx9v4SRMIoxJqrcK4RybRWLN2uEKbqxHCU/edit?usp=sharing) |  |  | **Grade 5:** [Earth Systems](https://docs.google.com/document/d/1sOIHKNs2d0KxKEKRS6MheTDQjP5frAYZ5FZW0ZvGGDQ/edit?usp=sharing) |  | **Grade 5:** [Space Systems: Stars and the Solar System](https://docs.google.com/document/d/10L9tFtVB_c709Agaz4Ta-4xbrJP4qddAhMDyMRQFnIE/edit?usp=sharing) |  |
| **Social Studies** | **Unit 1:**  [Geography of the Western Hemisphere](https://docs.google.com/document/d/1wXCzyizyC0T-G996Xj8-7_vBNtx00qbcDz9MkRzZYR4/edit?usp=sharing) |  | **Unit 2:**  [Ancient Civilizations](https://docs.google.com/document/d/1_ZWSod-BlM_qoa0aRoPuRy8RphenSYSvUQRrBA1ovXY/edit?usp=sharing) |  | **Unit3:**  [The Age of  Exploration](https://docs.google.com/document/d/1RFDmL3WBz9Kv9ndzBxqtvuW_5RR-KOgKgeiSbdZyRVw/edit?usp=sharing) |  | **[PBL–  World's Fair](https://docs.google.com/document/d/1MMS1pPYp6UWd4RV75MFZucdINCAf8dd8d-iOxW9riUw/edit?usp=sharing) – is not gaining any traction and is currently on hold** |  |  |  |
|  |  |  |  |  |  |  | Currently not taught: **Unit 4:** Gov't and Econ of West Hem |  | **Unit5; (Is this considered ELA?)** We the People/ SC Mock Case |  |
`,
};
